name = "DelvesLynessBeyn"
uuid = "4c43038d-41d7-44de-8c6a-75c6a53f7eba"
authors = ["James Cook <cookjws@gmail.com>"]
version = "0.1.0"

[deps]
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
FFTW = "1.10.0"
LinearAlgebra = "1.11.0"
Random = "1.11.0"
Test = "1.11.0"

[extras]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Random", "Test"]
